debug: true
logging:
  level:
    root: info
  file:
    path: d:/springbootproj.log
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    data-username: root
    data-password: 123456
mall:
  config:
    name: 爱美商城
    description: 这是一家化妆品专卖网站
    hot-sales: 20
    show-advert: true